### ISSUE TITLE
please add count_loaded_refs_in_load_order.pas

### ISSUE THREAD

**Issue by lex1975** [Meridiano/SkyrimSE-Head#2]
Please add this script count_loaded_refs_in_load_order.pas
https://gist.github.com/aers/953a50c61b3028bce7e5376e8590abed

into your repo.
And manual for this.
Read this: https://www.reddit.com/r/skyrimmods/comments/ag4wm7/psa_the_reference_handle_cap_or_diagnosing_one_of/

Спасибо за подробный мануал! Здоровья тебе!
Пожалуйста добавь этот скрипт в твой репозитарий и описалово, как запускать
Прочти тему на реддите по ссылке

**Comment by Meridiano** [comment]
Добавил в [Технические детали](https://github.com/Meridiano/SkyrimSE-Head/blob/master/02_Self_Help/02_Технические_детали.md), спасибо.
