### ISSUE TITLE
Edit in the manual regarding cleaning master files

### ISSUE THREAD

**Issue by lex1975** [Meridiano/SkyrimSE-Head#3]
Мне кажется, что судя по этому обсуждению:
https://www.reddit.com/r/skyrimmods/comments/8wh749/cleaning_masters_with_mo2_and_sseedit_cleaned/

необходимо изменить это руководство по очистке мастерфайлов:
https://github.com/Meridiano/SkyrimSE-Head/blob/master/01_Main_Info/03_Общий_порядок_действий.md

В части создания мода из мастер-файлов, а потом уже очистке этого мода через SSEEDIT.

[English]

It seems to me that judging by this discussion:
https://www.reddit.com/r/skyrimmods/comments/8wh749/cleaning_masters_with_mo2_and_sseedit_cleaned/

You need to change this guide for cleaning master files:
https://github.com/Meridiano/SkyrimSE-Head/blob/master/01_Main_Info/03_Общий_порядок_действий.md

In the part of creating a mod from the master files, and then clearing this mod via SSEEDIT.

**Comment by Meridiano** [comment]
1) Можно просто оставить бэкапы.
2) Если прилетит обнова на Update.esm, то в МО2 останется старый Update.esm, который может привести к проблемам. Нужно будет удалить его, скопировать в мод снова и почистить. Вместо того, чтобы просто почистить с созданием бэкапа.

**Comment by Meridiano** [comment]
Добавил как вариант. Спасибо!
